server:
  port: 8080

---

spring:
  profiles: default
  datasource:
    url: jdbc:mariadb://localhost:23306/goodteam
    driver-class-name: org.mariadb.jdbc.Driver
    username: DB아이디
    password: DB비번
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  # jpa:
  #   properties:
  #     hibernate:
  #       show_sql: true
  #       naming:
  #         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  #         check_nullability: true
  #       format_sql: true

---
server:
  port: 8080

spring:
  profiles: dev
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          replicationFactor: 1
          auto-create-topics: true
          brokers: goodteam-mq-kafka.edu-common:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        binding-in-sse:
          destination: evpowerguard
          content-type: application/json
          group: ev
        binding-out-sse:
          destination: evpowerguard
          content-type: application/json
          group: ev
logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: info
